# Generated by Django 6.0 on 2026-01-27 16:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learnapp', '0005_userdetails_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basename', models.CharField(choices=[('MAIDA', 'Maida'), ('WHEAT', 'Wheat')], max_length=100)),
                ('base_img', models.ImageField(blank=True, null=True, upload_to='base/')),
            ],
        ),
        migrations.CreateModel(
            name='FoodItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('foodpic', models.ImageField(blank=True, null=True, upload_to='foodpic/')),
                ('Categories', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('BIRIYANI', 'Biriyani'), ('PIZZA', 'Pizza'), ('BURGER', 'Burger'), ('DESSARTS', 'Dessarts'), ('BREVERAGES', 'Beverages')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sauce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(choices=[('RED CHILLI', 'Red chilli'), ('TOMATO', 'Tomato'), ('GREEN CHILLI', 'Green chilli')], max_length=100)),
                ('price', models.IntegerField()),
                ('sause_img', models.ImageField(blank=True, null=True, upload_to='sauce/')),
            ],
        ),
        migrations.CreateModel(
            name='Sizechart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('REGULAR', 'Regular'), ('MEDIUM', 'Medium'), ('LARGE', 'Large')], max_length=100)),
                ('size_in_cm', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Toppings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SWEETCORN', 'Sweetcorn'), ('PANEER', 'Paneer'), ('ONION', 'Onion'), ('CHEESE', 'Cheese'), ('OLIVE', 'Olive'), ('CAPSICUM', 'Capsicum'), ('CHICKEN', 'Chicken'), ('CHICKEN SALAMI', 'Chicken Salami'), ('CHICKEN SAUSAGE', 'Chicken Sausage'), ('BARBEQUE CHICKEN', 'Barbeque Chicken'), ('EGG', 'Egg'), ('LETTUCE', 'Lettuce')], max_length=100)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('topping_img', models.ImageField(blank=True, null=True, upload_to='topping/')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('rating', models.FloatField()),
                ('quantity', models.IntegerField(default=1)),
                ('food_img', models.ImageField(blank=True, null=True, upload_to='cart/')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.fooditems')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('total_qty', models.PositiveIntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='learnapp.userdetails')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.fooditems')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='foods.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnapp.userdetails')),
            ],
        ),
        migrations.CreateModel(
            name='customizeoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_type', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('BIRIYANI', 'Biriyani'), ('PIZZA', 'Pizza'), ('BURGER', 'Burger'), ('DESSARTS', 'Dessarts'), ('BREVERAGES', 'Beverages')], max_length=100)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basetypes', to='foods.basetype')),
                ('sauce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sauces', to='foods.sauce')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizecharts', to='foods.sizechart')),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toppings', to='foods.toppings')),
            ],
        ),
    ]
