# Generated by Django 6.0 on 2026-01-30 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_remove_cart_food_remove_cart_rating_cart_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
