# Generated by Django 6.0 on 2026-02-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customizeoption',
            name='topping',
        ),
        migrations.AddField(
            model_name='customizeoption',
            name='topping',
            field=models.ManyToManyField(to='foods.toppings'),
        ),
    ]
