# Generated by Django 6.0 on 2026-02-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0006_remove_customizeoption_topping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toppings',
            name='category',
            field=models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('BIRIYANI', 'Biriyani'), ('PIZZA', 'Pizza'), ('BURGER', 'Burger'), ('DESSARTS', 'Dessarts'), ('BREVERAGES', 'Beverages')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
