# Generated by Django 6.0 on 2026-02-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0007_toppings_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizeoption',
            name='topping',
            field=models.ManyToManyField(blank=True, null=True, to='foods.toppings'),
        ),
    ]
