# Generated by Django 6.0 on 2026-01-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnapp', '0002_userdetails_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='phone',
            field=models.BigIntegerField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='userpic',
            field=models.ImageField(blank=True, null=True, upload_to='userpic/'),
        ),
    ]
