# Generated by Django 6.0 on 2026-01-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnapp', '0003_alter_userdetails_phone_alter_userdetails_userpic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
