# Generated by Django 6.0 on 2026-01-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnapp', '0004_alter_userdetails_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='user_type',
            field=models.CharField(choices=[('USER', 'user'), ('VENDOR', 'vendor')], default='user', max_length=100),
        ),
    ]
